services:
  facebook-clone-db:
    container_name: facebook-clone-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: facebook-db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - facebook-clone-db:/var/lib/mysql
    networks:
      - facebook-clone-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "facebook-clone-db", "--password=password" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  facebook-clone-api:
    container_name: facebook-clone
    image: gitpatrickv/facebook-clone:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - facebook-clone-network
    depends_on:
      facebook-clone-db:
        condition: service_healthy
#    volumes:
#      - ./images:/app/images


volumes:
  facebook-clone-db:

networks:
  facebook-clone-network:
    driver: bridge
