services:
  facebook-clone-db:
    container_name: facebook-clone-db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: facebook-db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - facebook-clone-db:/var/lib/mysql
    networks:
      - facebook-clone-network
  facebook-clone-api:
    container_name: facebook-clone
    image: gitpatrickv/facebook-clone:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - facebook-clone-network
    depends_on:
      - facebook-clone-db
#    volumes:
#      - ./images:/app/images

  flyway:
    image: flyway/flyway
    container_name: facebook-clone-flyway
    environment:
      - FLYWAY_URL=jdbc:mysql://facebook-clone-db:3306/facebook-db
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=password
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - facebook-clone-db
    networks:
      - facebook-clone-network

volumes:
  facebook-clone-db:

networks:
  facebook-clone-network:
    driver: bridge



