spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    url: jdbc:mysql://facebook-clone-db:3306/facebook-db
#    password: password
    url: jdbc:mysql://localhost:3306/facebook-db
    password: patrick
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

application:
  security:
    jwt:
      secret-key: 6jZy59I3gNLH1Pj45sJT9/E0SSQUA1yNcAV1yZaXiwE
      expiration: 604800000 # 1 week